# Generated by Django 4.0.3 on 2022-07-21 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(choices=[('A', 'dhmotiko_a'), ('B', 'dhmotiko_b'), ('C', 'dhmotiko_c'), ('D', 'dhmotiko_d'), ('E', 'dhmotiko_e'), ('ST', 'dhmotiko_st'), ('GA', 'gymnasio_a'), ('GB', 'gymnasio_b'), ('GC', 'gymnasio_c'), ('LA', 'lykeio_a'), ('LB', 'lykeio_b'), ('LC', 'lykeio_c')], default='A', max_length=2)),
                ('class_number', models.IntegerField(default=1)),
                ('maximum', models.IntegerField()),
            ],
            options={
                'unique_together': {('classname', 'class_number')},
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('onoma', models.CharField(max_length=20)),
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('taxh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.classroom')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.teacher')),
            ],
            options={
                'unique_together': {('onoma', 'taxh')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(default='student_pics/default.png', upload_to='student_pics')),
                ('apousies', models.IntegerField(default=0)),
                ('taxh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(default=0)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.classroom')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.student')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.teacher')),
            ],
        ),
    ]
