# Generated by Django 4.0.3 on 2022-08-18 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='students_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='grades',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='grades',
            unique_together={('student', 'subject_name')},
        ),
    ]
