# Generated by Django 4.0.3 on 2022-09-23 07:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('pdf_question', models.FileField(blank=True, upload_to='assigments')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('question', models.CharField(blank=True, max_length=1000)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Subject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.subject')),
                ('classroom', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.classroom')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'school_manager'), (2, 'school_teacher'), (3, 'student'), (4, 'no_role')], null=True),
        ),
        migrations.CreateModel(
            name='StudentAssigments',
            fields=[
                ('file', models.FileField(blank=True, upload_to='student_assigments')),
                ('score', models.IntegerField(blank=True, default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.assignments')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.student')),
            ],
            options={
                'unique_together': {('student', 'Assignment')},
            },
        ),
    ]
