# Generated by Django 4.0.3 on 2022-09-23 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='taxh',
            new_name='classroom',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='taxh',
            new_name='classroom',
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('onoma', 'classroom')},
        ),
    ]
