# Generated by Django 4.0.3 on 2022-09-02 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_assignments_alter_user_role_studentassigments_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignments',
            name='teacher',
        ),
    ]
