# Generated by Django 4.0.3 on 2022-09-09 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_assignments_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassigments',
            name='score',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
