# Generated by Django 4.0.3 on 2022-09-23 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_taxh_student_classroom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignments',
            old_name='Subject',
            new_name='subject',
        ),
    ]
