# Generated by Django 4.0.3 on 2022-09-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_studentassigments_score_delete_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='deadline',
            field=models.DateTimeField(),
        ),
    ]
