# Generated by Django 4.0.3 on 2022-09-23 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_subject_assignments_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignments',
            old_name='subject',
            new_name='Subject',
        ),
    ]
