# Generated by Django 4.0.3 on 2023-02-09 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='deadline',
            field=models.DateField(),
        ),
    ]
