# Generated by Django 4.0.3 on 2023-02-10 23:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_announcements'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcements',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
