# Generated by Django 4.0.3 on 2023-02-19 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_announcements_created_alter_announcements_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.teacher'),
            preserve_default=False,
        ),
    ]
